INSERT INTO sub_industries(name, base_score, industry_id) VALUES ('Поликлиника',5.0, 1);
INSERT INTO sub_industries(name, base_score, industry_id) VALUES ('ОптикЦентр', 5.0, 1);
INSERT INTO sub_industries(name, base_score, industry_id) VALUES ('ФитнесКлуб', 4.0, 2);
INSERT INTO sub_industries(name, base_score, industry_id) VALUES ('Спортивная площадка', 4.0, 2);
INSERT INTO sub_industries(name, base_score, industry_id) VALUES ('Супер Маркет', 3.0, 3);
INSERT INTO sub_industries(name, base_score, industry_id) VALUES ('Алкомаркет', 1.0, 3);
INSERT INTO sub_industries(name, base_score, industry_id) VALUES ('Магазин здорового питания', 4.0, 3);
INSERT INTO sub_industries(name, base_score, industry_id) VALUES ('Аптека', 5.0, 3);
INSERT INTO sub_industries(name, base_score, industry_id) VALUES ('Фастфуд', 3.0, 4);
INSERT INTO sub_industries(name, base_score, industry_id) VALUES ('Столовая', 3.0, 4);
INSERT INTO sub_industries(name, base_score, industry_id) VALUES ('Бар', 1.0, 4);
INSERT INTO sub_industries(name, base_score, industry_id) VALUES ('Кафе здорового меню', 5.0, 4);
INSERT INTO sub_industries(name, base_score, industry_id) VALUES ('Завод', 1.0, 5);
INSERT INTO sub_industries(name, base_score, industry_id) VALUES ('Лесопереработка', 1.0, 5);
INSERT INTO sub_industries(name, base_score, industry_id) VALUES ('Заправка', 3.0, 5);
INSERT INTO sub_industries(name, base_score, industry_id) VALUES ('Мусорный полигон', 3.0, 6);
INSERT INTO sub_industries(name, base_score, industry_id) VALUES ('Сортировочный центр', 3.0, 6);
INSERT INTO sub_industries(name, base_score, industry_id) VALUES ('Городская свалка', 1.0, 6);
INSERT INTO sub_industries(name, base_score, industry_id) VALUES ('Пруд', 5.0, 7);
INSERT INTO sub_industries(name, base_score, industry_id) VALUES ('Водоем', 5.0, 7);
INSERT INTO sub_industries(name, base_score, industry_id) VALUES ('Сквер', 5.0, 7);